plugin:
  name: custom-data-type-gazetteer
  version: 1.0
  url: https://github.com/programmfabrik/easydb-custom-data-type-gazetteer
  displayname:
    de-DE: Gazetteer
    en-US: Gazetteer
  info:
    de-DE: Plugin for https://gazetteer.dainst.org
    en-US: Plugin for https://gazetteer.dainst.org
  server:
    api-version:
      require: 1
  webfrontend:
    url: custom-data-type-gazetteer.js
    css: custom-data-type-gazetteer.css
    logo: image/logo.png
    l10n: l10n/

python-2:
  file: src/server/gazetteer_insert.py

custom_types:
  gazetteer:
    update:
      script: build/scripts/gazetteer-update.js
      timeout: 10
      batch_size: 1000
      interval_base_config: update_interval_gazetteer.days
    mapping:
      gazId:
        type: text_oneline
      displayName:
        type: text

base_config:
  - name: update_interval_gazetteer
    group: update_custom_data_type
    parameters:
      days:
        type: int
        min: 0
        default: 1
        position: 0
  - name: gazetteer_plugin_settings
    group: gazetteer_plugin
    parameters:
      enabled:
        type: bool
        position: 0
        default: false
      objecttype:
        type: text
        position: 1
        plugin_type: "objecttype"
      field_from:
        type: text
        position: 2
        plugin_type: "field_from"
      field_to:
        type: text
        position: 3
        plugin_type: "field_to"
